# Custom values for Curity Identity Server Helm Chart.
# Please refer to https://github.com/curityio/idsvr-helm/blob/master/idsvr/README.md for exhaustive set of configuration options.

# -----------------------------------------------------------------------------
# Deployment parameters
# -----------------------------------------------------------------------------

curity:
  config:
    uiEnabled: true
    configuration:
        - secretRef:
            name: idsvr-config
            items:
              - key: license.json
                path: license/license.json
    configurationSecret: idsvr-config
    configurationSecretItemName: idsvr-cluster-config.xml

  admin:
    logging:
      level: DEBUG
  
  runtime:
    logging:
      level: DEBUG  

ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    runtime:
      host: login.example.gke
      secretName: example-gke-tls
      paths:
        - /
    admin:
      host: admin.example.gke
      secretName: example-gke-tls