
# Custom values for database less and declartative configuration Kong's Helm Chart.
# Please refer to https://github.com/Kong/charts/blob/main/charts/kong/values.yaml for exhaustive set of configuration options.

# -----------------------------------------------------------------------------
# Deployment parameters
# -----------------------------------------------------------------------------

image:
  repository: curity/kong-custom
  tag: "2.8.1-alpine"

dblessConfig:
  configMap: kong-declarative-config


admin:   # set enabled to true for creating a Kubernetes service for the admin API
  enabled: true
  type: ClusterIP

proxy: # set enabled to true for creating a Kubernetes service for the proxy API
  enabled: true
  type: ClusterIP

ingressController:
  enabled: false
  installCRDs: false

env:
  database: "off"
  plugins: 'bundled,phantom-token'