
# Custom values for database less and declartative configuration Kong's Helm Chart.
# Please refer to https://github.com/Kong/charts/blob/main/charts/kong/values.yaml for exhaustive set of configuration options.

# -----------------------------------------------------------------------------
# Deployment parameters
# -----------------------------------------------------------------------------

image:
  repository: curity/kong-custom
  tag: "2.8.1-alpine"

proxy:
  enabled: true
  type: LoadBalancer

ingressController:
  enabled: true
  installCRDs: false
  ingressClass: kong
  ingressClassAnnotations: {}
  rbac:
    create: true

# Temporary workaround: disable HTTP2 on admin endpoint
# https://github.com/Kong/kubernetes-ingress-controller/issues/2435
admin:
  tls:
    parameters: []

env:
  database: "off"
  LOG_LEVEL: "error"
  plugins: 'bundled,phantom-token' 